#!/bin/bash

GOOSE_DRIVER=clickhouse

CLICKHOUSE_USER=default
CLICKHOUSE_PASSWORD=changeme
CLICKHOUSE_HOST=localhost
CLICKHOUSE_PORT=9000

GOOSE_DBSTRING="clickhouse://$CLICKHOUSE_USER:$CLICKHOUSE_PASSWORD@$CLICKHOUSE_HOST:$CLICKHOUSE_PORT/$CLICKHOUSE_DATABASE"

# ?sslmode=disable