name: 'Install & Remove xbatd RPM'
description: 'Tests installing and removing the built xbatd RPM in a container'
inputs:
  distro:
    description: 'Target distro (el8 or el9)'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Download RPM artifact
      uses: actions/download-artifact@v4
      with:
        name: rpm-${{ inputs.distro }}
        path: ./rpms

    - name: Run container and test install/remove
      shell: bash
      run: |
        case "${{ inputs.distro }}" in
          el8)
            IMAGE="almalinux:8"
            ;;
          el9)
            IMAGE="almalinux:9"
            ;;
          *)
            echo "Unsupported distro: ${{ inputs.distro }}" >&2
            exit 1
            ;;
        esac

        docker run --rm -v "$(pwd)/rpms:/rpms" "$IMAGE" \
          bash -c "
            dnf install -y epel-release dnf-utils &&
            dnf install -y /rpms/*.rpm &&
            dnf remove -y xbatd
          "
