name: Build and Test xbatd RPM

on:
  push:
    branches:
      - ci-testing
  pull_request:
    branches:
      - ci-testing

jobs:
  build-el8:
    name: Build xbatd RPM for AlmaLinux 8
    runs-on: ubuntu-latest
    steps:
      - name: Build xbatd (el8)
        uses: ./github/actions/build-xbat
        with:
          version: '1.0.0'
          release: 'rc0'
          distro: 'el8'
          executor: 'docker'

  build-el9:
    name: Build xbatd RPM for AlmaLinux 9
    runs-on: ubuntu-latest
    steps:
      - name: Build xbatd (el9)
        uses: ./github/actions/build-xbat
        with:
          version: '1.0.0'
          release: 'rc0'
          distro: 'el9'
          executor: 'docker'

  install-test-el8:
    name: Install and remove RPM on AlmaLinux 8 container
    runs-on: ubuntu-latest
    needs: build-el8
    steps:
      - name: Test install/remove on el8
        uses: ./github/actions/install-test
        with:
          distro: 'el8'

  install-test-el9:
    name: Install and remove RPM on AlmaLinux 9 container
    runs-on: ubuntu-latest
    needs: build-el9
    steps:
      - name: Test install/remove on el9
        uses: ./github/actions/install-test
        with:
          distro: 'el9'
