name: Build and Test xbat daemon
# Trigger-Test, keine Änderung an der Logik

on:
  push:
    branches:
      - ci-testing
  pull_request:
    branches:
      - ci-testing

jobs:
  el8:
    name: Build, Install and Test on AlmaLinux 8
    runs-on: ubuntu-latest
    container:
      image: almalinux:8
    steps:
      - uses: actions/checkout@v4

      - name: Build with build.sh (el8)
        working-directory: src/xbatd
        run: ./build.sh 1.0.0 --release rc0 --distro el8 --executor docker

      - name: Find RPM (el8)
        working-directory: src/xbatd
        id: get_rpm
        run: |
          RPM_NAME=$(ls xbatd-1.0.0-rc0.el8*.rpm)
          echo "rpm_name=$RPM_NAME" >> "$GITHUB_OUTPUT"

      - name: Install dependencies for service
        run: dnf install -y which tar gzip

      - name: Install RPM (el8)
        run: dnf install -y src/xbatd/${{ steps.get_rpm.outputs.rpm_name }}

      - name: Run setup.sh install
        working-directory: src/xbat
        run: ./setup.sh install --home-mnt /home/ --executor docker --workers 4

      - name: Run setup.sh uninstall
        working-directory: src/xbat
        run: ./setup.sh uninstall

      - name: Remove RPM (el8)
        run: dnf remove -y xbatd || true

  el9:
    name: Build, Install and Test on AlmaLinux 9
    runs-on: ubuntu-latest
    container:
      image: almalinux:9
    steps:
      - uses: actions/checkout@v4

      - name: Build with build.sh (el9)
        working-directory: src/xbatd
        run: ./build.sh 1.0.0 --release rc0 --distro el9 --executor docker

      - name: Find RPM (el9)
        working-directory: src/xbatd
        id: get_rpm
        run: |
          RPM_NAME=$(ls xbatd-1.0.0-rc0.el9*.rpm)
          echo "rpm_name=$RPM_NAME" >> "$GITHUB_OUTPUT"

      - name: Prepare AlmaLinux 9 for dependencies
        run: |
          dnf install -y epel-release dnf-utils python3-pip which tar gzip
          dnf config-manager --set-enabled crb
          dnf update -y
          pip3 install wheel
          dnf install -y https://repo.radeon.com/amdgpu-install/6.4.1/rhel/9.6/amdgpu-install-6.4.60401-1.el9.noarch.rpm
          sed -i 's|/el/9.6/|/el/9.2/|g' /etc/yum.repos.d/amdgpu*.repo

      - name: Install RPM (el9)
        run: dnf install -y src/xbatd/${{ steps.get_rpm.outputs.rpm_name }}

      - name: Run setup.sh install
        working-directory: src/xbat
        run: ./setup.sh install --home-mnt /home/ --executor docker --workers 4

      - name: Run setup.sh uninstall
        working-directory: src/xbat
        run: ./setup.sh uninstall

      - name: Remove RPM (el9)
        run: dnf remove -y xbatd || true
